[aws]
symbol = "îŒ½  "

[buf]
format = "via [$symbol]($style)"
symbol = "ï’ "

[bun]
format = "via [$symbol]($style)"
symbol = "î¯ "

[c]
symbol = "î˜ "

[cmake]
format = "via [$symbol]($style)"
symbol = "î” "

[cobol]
format = "via [$symbol]($style)"

[conda]
symbol = "ï„Œ "

[cpp]
symbol = "î˜ "

[crystal]
format = "via [$symbol]($style)"
symbol = "î˜¯ "

[daml]
format = "via [$symbol]($style)"

[dart]
format = "via [$symbol]($style)"
symbol = "î˜ "

[deno]
format = "via [$symbol]($style)"
symbol = "îŸ€ "

[directory]
read_only = " ó°Œ¾"

[docker_context]
symbol = "ïŒˆ "

[dotnet]
format = "[$symbol(ğŸ¯ $tfm )]($style)"

[elixir]
format = "via [$symbol]($style)"
symbol = "î˜­ "

[elm]
format = "via [$symbol]($style)"
symbol = "î˜¬ "

[erlang]
format = "via [$symbol]($style)"

[fennel]
format = "via [$symbol]($style)"
symbol = "îš¯ "

[fossil_branch]
symbol = "ï˜ "

[gcloud]
symbol = "îŒ½  "

[git_branch]
symbol = "ï˜ "

[git_commit]
tag_symbol = " ï’ "

[gleam]
format = "via [$symbol]($style)"

[golang]
format = "via [$symbol]($style)"
symbol = "î˜§ "

[gradle]
format = "via [$symbol]($style)"
symbol = "î™  "

[guix_shell]
symbol = "ïŒ¥ "

[haskell]
symbol = "î· "

[haxe]
format = "via [$symbol]($style)"
symbol = "î™¦ "

[helm]
format = "via [$symbol]($style)"

[hg_branch]
symbol = "ï˜ "

[hostname]
ssh_symbol = "î¬ "

[java]
format = "via [$symbol]($style)"
symbol = "î‰– "

[julia]
format = "via [$symbol]($style)"
symbol = "î˜¤ "

[kotlin]
format = "via [$symbol]($style)"
symbol = "î˜´ "

[lua]
format = "via [$symbol]($style)"
symbol = "î˜  "

[memory_usage]
symbol = "ó°› "

[meson]
format = "via [$symbol]($style)"
symbol = "ó°”· "

[nim]
format = "via [$symbol]($style)"
symbol = "ó°†¥ "

[nix_shell]
symbol = "ïŒ“ "

[nodejs]
format = "via [$symbol]($style)"
symbol = "îœ˜ "

[ocaml]
format = "via [$symbol(\\($switch_indicator$switch_name\\) )]($style)"
symbol = "î™º "

[opa]
format = "via [$symbol]($style)"
[os.symbols]
AlmaLinux = "ïŒ "
Alpaquita = "îª¢ "
Alpine = "ïŒ€ "
Amazon = "ï‰° "
Android = "ï…» "
Arch = "ïŒƒ "
Artix = "ïŒŸ "
CachyOS = "ïŒƒ "
CentOS = "ïŒ„ "
Debian = "ïŒ† "
DragonFly = "îŠ "
Emscripten = "ïˆ… "
EndeavourOS = "ï†— "
Fedora = "ïŒŠ "
FreeBSD = "ïŒŒ "
Garuda = "ó°›“ "
Gentoo = "ïŒ "
HardenedBSD = "ó°Œ "
Illumos = "ó°ˆ¸ "
Kali = "ïŒ§ "
Linux = "ïŒš "
Mabox = "î¬© "
Macos = "ïŒ‚ "
Manjaro = "ïŒ’ "
Mariner = "ï‡ "
MidnightBSD = "ï†† "
Mint = "ïŒ "
NetBSD = "ï€¤ "
NixOS = "ïŒ“ "
Nobara = "ï€ "
OpenBSD = "ó°ˆº "
OracleLinux = "ó°Œ· "
Pop = "ïŒª "
Raspbian = "ïŒ• "
RedHatEnterprise = "ïŒ– "
Redhat = "ïŒ– "
Redox = "ó°€˜ "
RockyLinux = "ïŒ« "
SUSE = "ïŒ” "
Solus = "ó° ³ "
Ubuntu = "ïŒ› "
Unknown = "ïˆ­ "
Void = "ïŒ® "
Windows = "ó°² "
openSUSE = "ïŒ” "

[package]
symbol = "ó°— "

[perl]
format = "via [$symbol]($style)"
symbol = "î™¾ "

[php]
format = "via [$symbol]($style)"
symbol = "î˜ˆ "

[pijul_channel]
symbol = "ï˜ "

[pixi]
format = "via [$symbol($environment )]($style)"
symbol = "ó°— "

[pulumi]
format = "via [$symbol$stack]($style)"

[purescript]
format = "via [$symbol]($style)"

[python]
format = "(\\($virtualenv\\) )via [$symbol]($style)"
symbol = "îˆµ "

[quarto]
format = "via [$symbol]($style)"

[raku]
format = "via [$symbol]($style)"

[red]
format = "via [$symbol]($style)"

[rlang]
format = "via [$symbol]($style)"
symbol = "ó°Ÿ” "

[ruby]
format = "via [$symbol]($style)"
symbol = "î‘ "

[rust]
format = "via [$symbol]($style)"
symbol = "ó±˜— "

[scala]
symbol = "îœ· "

[solidity]
format = "via [$symbol]($style)"

[swift]
format = "via [$symbol]($style)"
symbol = "î• "

[typst]
format = "via [$symbol]($style)"

[vagrant]
format = "via [$symbol]($style)"

[vlang]
format = "via [$symbol]($style)"

[zig]
format = "via [$symbol]($style)"
symbol = "îš© "
